# Generated by Django 3.2 on 2021-04-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('price', models.FloatField(verbose_name='price')),
                ('multiple', models.PositiveIntegerField(verbose_name='multiplo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, verbose_name='quantidade')),
                ('total', models.FloatField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.PositiveIntegerField(verbose_name='produto')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('price', models.FloatField(verbose_name='preço')),
                ('total', models.FloatField()),
                ('rentability', models.IntegerField(choices=[(1, 'Great'), (2, 'Good'), (3, 'Bad')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ('-id',),
            },
        ),
    ]
