# Generated by Django 3.2 on 2021-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210413_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rentability',
            field=models.IntegerField(choices=[(1, 'Ótima'), (2, 'Boa'), (3, 'Ruim')]),
        ),
    ]
