# Generated by Django 3.2 on 2021-04-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210413_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rentability',
            field=models.IntegerField(blank=True, choices=[(1, 'Ótima'), (2, 'Boa'), (3, 'Ruim')], null=True),
        ),
    ]
