# Generated by Django 3.2 on 2021-04-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_rentability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rentability',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantidade'),
        ),
    ]
