# Generated by Django 3.2 on 2021-04-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210416_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rentability',
            field=models.IntegerField(blank=True, choices=[(1, 'Ótima'), (2, 'Boa'), (3, 'Ruim')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
