# Generated by Django 3.2 on 2021-04-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210416_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rentability',
            field=models.IntegerField(blank=True, choices=[(1, 'Ótima'), (2, 'Boa'), (3, 'Ruim')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
