# Generated by Django 3.2 on 2021-04-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210417_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rentability',
            field=models.IntegerField(choices=[(1, 'Ótima'), (2, 'Boa'), (3, 'Ruim')], default=2),
        ),
    ]
